name: Main workflow
on: push
env: # Set the secret as an input
  docker_username: ${{ github.actor }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: bash ci/build-app.sh
      - name: Test
        run: bash ci/unit-test-app.sh
      - uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  # Linting:
  #   runs-on: ubuntu-latest
  #   needs: [Build]
  #   steps:
  #     - name: Download code
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: code
  #         path: .
  #     - name: run linting
  #       uses: super-linter/super-linter/slim@v5 
  #       env:
  #         DEFAULT_BRANCH: main
  #         # To report GitHub Actions status checks
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Get Short Commit SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: build docker
        run: bash ci/build-docker.sh ${{ env.SHORT_SHA }}
      - name: push docker
        run: bash ci/push-docker.sh ${{ env.SHORT_SHA }}
